### ISSUE TITLE
Creating an image that can be used in .gitlab-ci.yml

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#504]
## Summary

From slack support [thread](https://cloud-native.slack.com/archives/C033DV8D9FB/p1656690549243849?thread_ts=1656585004.426589&cid=C033DV8D9FB):

---

GitLab CI tries to augment the entrypoint causing issues with images that have a preset entrypoint like images produced by buildpacks (since we want to run the launcher). See [this issue](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2692) and [docs](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#override-the-entrypoint-of-an-image) for more info.

You may emulate the necessary configuration for local testing by using a simple docker command:

```
docker --rm -it --entrypoint='' <my-image> <script>
```

This would then be converted to .gitlab-ci.yml as:

```
  image:
    name: <my-image>
    entrypoint: [""] # force an empty entrypoint
  script:
    - <script>
```

In most cases, you can use Procfile to create a web process with the parameters you need.

Then the following should work locally:

```
docker --rm -it --entrypoint='' <my-image> web
```

Then your .gitlab-ci.yml file should be:

```
  image:
    name: <my-image>
    entrypoint: [""] # force an empty entrypoint
  script:
    - web
```

## What questions should this documentation answer?
- Why do I need to configure `.gitlab-ci.yml` differently for images produced by buildpacks?
- How do I configure `.gitlab-ci.yml`?

## Who is the target audience for this documentation?

- [x] App Developer
- [ ] Buildpack Author
- [x] Operator
- [ ] Other:
